#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

# for jq
PATH=/usr/local/bin:$PATH

payload=$TMPDIR/codebuild-resource-request

cat > $payload <&0

project=$(jq -r '.source.project // ""' < $payload)
role_arn=$(jq -r '.source.role_arn // ""' < $payload)
ref=$(jq -r '.version.ref // ""' < $payload)

if [ -z "$ref" ]; then
  ref=NEVERGONNAEXIST
fi

if [ -n "$role_arn" ]; then
  assume_role "$role_arn"
fi

{
    set -f
    aws codebuild list-builds-for-project --project-name "$project" --query 'ids[*]'
    set +f
} | jq ".[]" | sed "/$ref/ q" | tail -r | jq -s "map({ref: .})"