#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

sources=$1

if [ -z "$sources" ]; then
  echo "usage: $0 <path/to/sources>" >&2
  exit 1
fi

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp $TMPDIR/codebuild-resource-request.XXXXXX)

cat > $payload <&0

project=$(jq -r '.source.project // ""' < $payload)
region=$(jq -r '.source.region // ""' < $payload)
role_arn=$(jq -r '.source.role_arn // ""' < $payload)
env_var_overrides=$(jq -r '.params.env_var_overrides // []' < $payload)

if [ -z "$region" ]; then
    region=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq .region -r)
fi

export AWS_REGION=$region
export AWS_DEFAULT_REGION=$region

if [ -n "$role_arn" ]; then
  assume_role "$role_arn"
fi

jq -n "{
    \"projectName\": \"$project\", 
    \"environmentVariablesOverride\": $env_var_overrides
}" > /tmp/build_input.json

echo "Starting to build project $project"
BUILD_ID=$(aws codebuild start-build --query 'build.id' --output text --region "$region" --cli-input-json file:///tmp/build_input.json)
echo "Started build $BUILD_ID"

# The log group is typically not ready right away
sleep 2

# Kick off the log streaming in the background
watch_build_logs "$BUILD_ID" &
LOG_JOB=%1

# Wait for the codebuild to report as anything but IN_PROGRESS
wait_for_build_to_finish "$BUILD_ID"
echo "Build job has finished"
ps -a
echo "Killing the logging job"
jobs
kill $LOG_JOB
jobs
ps -a

jq -n "{
  version: {
    ref: $(echo $BUILD_ID | jq -R .)
  },
  metadata: [
    { name: \"project\", value: \"$project\" }
  ]
}" >&3
